baseURL = "https://kyawmyintthein.github.io/"
title = "Kyaw Myint Thein | Personal Blog"
theme = "PaperMod"
copyright = "© 2024 Kyaw Myint Thein"
languageCode = "en-us"
defaultContentLanguage = "en"

# Global parameters
[params]
  env = "production"
  description = "Senior Software Engineer sharing insights on technology, life, travel adventures, and experiences from Sydney, Australia"
  keywords = ["technology", "personal-blog", "travel", "trekking", "road-trips", "life-in-sydney", "software-engineering", "myanmar", "australia", "youtube"]
  author = "Kyaw Myint Thein"

  # Theme settings
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = true
  tocopen = false

  # Social icons
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/kyawmyintthein"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/kyaw-myint-thein"

  [[params.socialIcons]]
    name = "youtube"
    url = "https://www.youtube.com/@AwesomelyWeirdWanderers"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:kyawmyintthein2020@gmail.com"

  # Profile mode with profile photo
[params.profileMode]
  enabled = true
  title = "Kyaw Myint Thein (Joe)"
  subtitle = "Senior Software Engineer from Myanmar, currently living in Sydney. Sharing thoughts on technology, life, and everything in between."
  imageUrl = "/images/profile-square.jpg"
  imageWidth = 240
  imageHeight = 240
  imageTitle = "Joe's Profile Photo"

  # Profile mode buttons
  [[params.profileMode.buttons]]
    name = "Blog"
    url = "/blog"

  [[params.profileMode.buttons]]
    name = "About"
    url = "/about"

  [[params.profileMode.buttons]]
    name = "Tags"
    url = "/tags"

  # Home info mode (disabled when profile mode is enabled)
  [params.homeInfoParams]
    Title = "Hi, I'm Joe 👋"
    Content = "Welcome to my personal space on the web! I'm a software engineer from Myanmar currently living in Sydney, sharing stories about technology, life experiences, and everything that catches my interest."

# Navigation
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 2

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 3

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 4

# Markup configuration
[markup]
  [markup.highlight]
    style = "github"
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = false
    noClasses = false

  [markup.goldmark.renderer]
    unsafe = true

# Taxonomies
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

# Outputs
[outputs]
  home = ["HTML", "RSS", "JSON"]