name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - master  # Your repository uses master, not main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Clean all generated content
        run: |
          rm -rf ./public
          rm -rf ./resources/_gen
          echo "Cleaned all generated content and caches"

      - name: Build
        run: |
          echo "Building Hugo site with timestamp: $(date)"
          echo "Deployment timestamp: $(date)" > static/deployment-check.txt
          echo "Commit: ${{ github.sha }}" >> static/deployment-check.txt
          echo "Run number: ${{ github.run_number }}" >> static/deployment-check.txt
          hugo --minify --baseURL "${{ steps.pages.outputs.base_url }}/" --cleanDestinationDir
          echo "Build completed at $(date)"
          echo "Generated files:"
          ls -la ./public/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
          retention-days: 1

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          timeout: 600000
          error_count: 10
          reporting_interval: 5000

      - name: Verify deployment
        run: |
          echo "Deployment completed!"
          echo "Site URL: ${{ steps.deployment.outputs.page_url }}"
          echo "Waiting 30 seconds for propagation..."
          sleep 30
          echo "Testing site availability..."
          curl -I "${{ steps.deployment.outputs.page_url }}" || echo "Site not immediately available"
