name: GitHub Pages

on:
  push:
    branches:
      - master  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Clean and prepare build
        run: |
          rm -rf ./public
          echo "Cleaned public directory"

      - name: Build
        run: |
          echo "Building Hugo site..."
          hugo --minify --baseURL "${{ steps.pages.outputs.base_url }}/" --cleanDestinationDir
          echo "Build completed at $(date)"

      - name: List build output
        run: |
          echo "Contents of public directory:"
          ls -la ./public/
          echo "Sample of index.html:"
          head -20 ./public/index.html || echo "No index.html found"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

      - name: Deploy to GitHub Pages
        id: deployment
        if: github.ref == 'refs/heads/master' && success()
        uses: actions/deploy-pages@v4
